### ISSUE TITLE
Members/Maintenance/Name Tags buttons are squished together.

### ISSUE THREAD

**Issue by billtrowbridge** [secularHub/MembersApp#1]
I'm guessing: a CSS width problem on btn-custom class.

![2017-01-24](https://cloud.githubusercontent.com/assets/2688607/22240977/9dc843c0-e1da-11e6-8e0d-3ac7d51cc742.png)

**Comment by billtrowbridge** [comment]
Chrome Developer Tools mode may be helpful in determining the problem.  If you pick "Elements" tab at the top, and then click on various elements, the CSS that applies (and is computed) is shown in the upper-right corner.  If you hover on a computed value in the "computed" tab and click the tiny white arrow in black circle, it will take you directly to the source of the computed value.

Awesome tool !

I looked at width of the buttons, they're each different.  Maintenance is more than 100px wide.  The width of the "li" elements surrounding the buttons is constrained to 100.  That's part of the problem.  The styles ending with [_ngcontent-xyz-0] happens to be some Angular2 "magic" allowing it to insert multiple CSS files, but keep each CSS file applicable to it's own component.  Slick!  In this case, I know that _ngcontent-xyz-0 maps back to App.component.css, because it's the only one with width20.

It looks like these changes will fix it, but I haven't checked for side effects (breaking other lists):

- [ ] App.component.css line 72 in "ul li {...}", remove line "width: 100px;"
- [ ] App.component.css line 104 in "nav li {...}", remove line "margin-left:-20px;"

**Comment by dfangrow** [comment]
The CSS was modified and the buttons were standardized across the app. Many other CSS enhancements were done to standardize the look and feel between screens as well. I believe this issue can be closed.
