### ISSUE TITLE
CSS maintenance potential nightmare

### ISSUE THREAD

**Issue by billtrowbridge** [secularHub/MembersApp#3]
Right now maintenance.component.css and payment.component.css are almost, but not quite identical.  They differ by just a few lines.

A great deal of members.component.css is identical to them, and some of the rest is similar (i.e station vs station2).

There's also a lot of css in those files that we're not using.

navbar.component.css is beautiful.  All the component css ought to be similarly simple.

SOLUTION: The common parts of application css that we use should all be in src/styles.css .
For this tiny app, is there any good reason why all the application css can't be in that one file,
or at least all but a few tiny pieces in the component css files?

(Temporarily, I copied the contents of maintenance.component.css to nametags.component.css. It will need fixing, too.)

**Comment by billtrowbridge** [comment]
The only differences between maintenance.component.css (on left) and payment.component.css (on right) are:

in .itemtable class (~line 238):

maintenance | payment
-------------- | ----------
font-weight: 100; | font-weight: normal;
font-size: 9; | font-size: x-small;

and in maintenance.component.css in the ".itemtable tr th" at ~ line 261 it has:
'font-size: 10;'
which is not in payment.component.css at all.

**Comment by dfangrow** [comment]
A significant portion of the CSS used across the application has been moved to style step CSS and removed from the individual module CSS files. Additional CSS used only by modules still exists in the module. CSS files so I believe this issue is closed.
