### ISSUE TITLE
Add location /nametags to nginx default config file

### ISSUE THREAD

**Issue by billtrowbridge** [secularHub/MembersApp#4]
@dfangrow 

If you're up to it, and the bodies are all the same, try:
`location ~* ^\/(members|maintenance|nametags)$ { ... }`
Hopefully the ^ and $ will work, indicating the beginning and end of string.
The pattern means: match from the beginning of the string, first a literal slash, then either members or maintenance or nametags, and finally the end of the string.

If that works, bump it up a notch with this pattern:
`location ~* ^\/([^.]+)$ { ... }`
The pattern means: match from the beginning of the string, first a literal slash, then one or more of any characters except a period, and finally the end of the string.
The idea is to match the plain words used for any new components, but let others ( like css and js files) go back to the root handler.

I tested these patterns here:   http://www.regexpal.com/94055
I used these test strings.  This first 4 should match. The last 2 should not match.

/members
/maintenance
/nametags
/someNewComponent
/some.css
/any.js

**Comment by billtrowbridge** [comment]
Dave Fangrow fixed it.

**Comment by dfangrow** [comment]
Thanks Bill. I will review these and use the issues site more going forward.
